name: cifar10_pytorch_const
hyperparameters:
  learning_rate: 1.0e-4
  learning_rate_decay: 1.0e-6
  layer1_dropout: 0.25
  layer2_dropout: 0.25
  layer3_dropout: 0.5
  global_batch_size: 256
records_per_epoch: 50000
searcher:
  name: single
  metric: validation_error
  max_length:
    epochs: 32
entrypoint: model_def:CIFARTrial
min_validation_period:
  epochs: 1
resources:
  resource_pool: rocm-pool
  slots_per_trial: 8
environment:
  #image: determinedilia/environments:rocm-4.2-pytorch-1.9-rocm-5742da3
  image: determinedilia/environments:rocm-4.2-pytorch-1.9-rocm-62c0f21
