name: cifar10_tf_keras_const
data:
  url: https://s3-us-west-2.amazonaws.com/determined-ai-datasets/cifar10/cifar-10-python.tar.gz
hyperparameters:
  learning_rate: 1.0e-4
  learning_rate_decay: 1.0e-6
  layer1_dropout: 0.25
  layer2_dropout: 0.25
  layer3_dropout: 0.5
  global_batch_size: 32
  width_shift_range: 0.1
  height_shift_range: 0.1
  horizontal_flip: True
records_per_epoch: 50000
searcher:
  name: single
  metric: val_categorical_error
  max_length:
    epochs: 32
min_validation_period:
  epochs: 1
entrypoint: model_def:CIFARTrial
environment:
  image: determinedilia/environments:rocm-4.2-pytorch-1.9-rocm-e9238da
    #image: determinedilia/environments:rocm-4.2-pytorch-1.9-rocm-9042d69
    #image: determinedilia/environments:rocm-4.2-tf-2.5-rocm-0023787
resources:
  resource_pool: rocm-pool
  slots_per_trial: 1
